### ISSUE TITLE
3.2

### ISSUE THREAD

**Issue by costanzomoffa** [satanasov/phpbbgallery#158]
hi this ext function with 3.2

thx

**Comment by sentralgit** [comment]
Hello,

I faced some errors and also some broken UI elements. I guess this is due to changes in 3.2.

The broken UI can be fixed by changing <dl class="icon"> to <dl class="row-item">

Nevertheless I also faced some fatal errors like loadUsers() missing and the upload also does not work since an include is missing functions_upload.php. Please correct me if I may be wrong.
